### ISSUE TITLE
Dynamically size instance count of components based on AIs

### ISSUE THREAD

**Issue by bbyers-pivotal** [Pivotal-Field-Engineering/PCF-Sizer#8]

**Comment by rjain-pivotal** [comment]
Router "Qty" does not change as I move the AI counts from 200 to 500. What are you using for your calculation for the Routers? From what I can gather, it's more like a 50:1 (AI's to routers) as a starting point, although the GCP 250K AI deployment test is at about a 90:1 ratio. Thoughts? 

Best regards,

-Chris

**Comment by rjain-pivotal** [comment]
was looking to get a sense, from the sizer perspective, router to AI ratio. once I get to 5 routers (at 200 AIs) it stays at 5 routers even out to 15K AIs. is there a ratio rule of thumb as AIs increase?
- Paul

**Comment by bbyers-pivotal** [comment]
This has been resolved in the latest version. Each job is now dynamically scaled based on AIs selected
